# Generated by Django 4.2.5 on 2024-01-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='info.tag'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='tags',
            field=models.ManyToManyField(to='info.tag'),
        ),
    ]
