# Generated by Django 4.2.5 on 2023-12-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_customuser_departmment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='departmment',
            new_name='department',
        ),
    ]
