# Generated by Django 4.2.5 on 2023-12-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_rename_departmment_customuser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('bus_no', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bus_type', models.CharField(blank=True, max_length=20, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.day')),
            ],
        ),
    ]
