# Generated by Django 4.2.5 on 2023-12-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_busschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.day'),
        ),
    ]
