# Generated by Django 4.2.5 on 2024-01-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='info.tag'),
        ),
    ]
